# air.toml (fixed configuration)
root = "."
tmp_dir = "tmp"

[build]
# Use this for Windows:
cmd = "go build -o ./tmp/main.exe ./cmd/api"
# For Linux/Mac use:
# cmd = "go build -o ./tmp/main ./cmd/api"
bin = "tmp/main.exe"  # Windows
# bin = "tmp/main"    # Linux/Mac
include_dir = ["cmd", "internal", "Internal"]  # Added "Internal"
include_ext = ["go"]
exclude_dir = ["tmp", "vendor"]  # Exclude build artifacts

[run]
cmd = "tmp/main.exe"  # Windows
# cmd = "./tmp/main"  # Linux/Mac