version: "3"
services:
  db:
    image: postgres:15
    container_name: go_api_db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root123
      POSTGRES_DB: madevent
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: