# ---------- Build stage ----------
FROM golang:1.24-alpine AS builder

WORKDIR /app

# Install git (needed for go modules)
RUN apk add --no-cache git

# Cache dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy source code
COPY . .

# Build API binary
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -ldflags="-s -w" -o api ./cmd/api

# Build migrate binary
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -ldflags="-s -w" -o migrate ./cmd/migrate

# ---------- Final image ----------
FROM alpine:latest 

WORKDIR /app

# Copy binaries
COPY --from=builder /app/api .
COPY --from=builder /app/migrate .

# Copy migrations folder to correct location
COPY --from=builder /app/cmd/migrate/migrations ./migrations

# Expose API port
ENV PORT=8080
EXPOSE 8080

# Default run api
CMD ["./api"]