# ---------- Final image ----------
FROM alpine:latest
WORKDIR /app

# Copy binaries
COPY ../bin/api .
COPY ../bin/migrate .

# Ensure binaries are executable
RUN chmod +x api migrate

# Copy migrations
COPY ../cmd/migrate/migrations ./migrations

# Copy .env if needed
COPY ../.env .

# Expose port
ENV PORT=8080
EXPOSE 8080

# Default run
CMD ["./api"]
